config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'
    resources :products, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clothe.rb
class Clothe < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController

    def new
        @cloth= Cloth.new
    end

    def create
        Cloth.create(cloth_params)
        redirect_to new_product
    end

    def show
        @cloth = Cloth.find(params[:id])
    end

    private

    def cloth_params
        params.require(:cloth).permit(:product, :cost)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!

    def index
    end

    def new
    end

    def create
        Product.create(product_params)
        redirect_to root_path
    end

    def show
        @product = Product.find(params[:id])
    end

    private

    def product_params
        params.require(:product).permit(:product, :cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suprare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Suprare</a>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item active">
            <%= link_to 'Shoes', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Clothes', new_product_url, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Accessories</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
             <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/products/index.html.erb
<br />
<div class="hero">
    <br />
    <br />
    <div class="frosty col-10 offset-1 text-center">
            <h1>BUY AND SELL THE MOST RARE SHOES, CLOTHES, AND ACCESSORIES</h1>
    </div>
</div>

<br />
<div class="booyah-box col-10 offset-1">
    <h1>Shoes</h1>
    <%= simple_form_for root_path do |f| %>
        <%= f.input :product %>
        <%= f.input :cost %>
        <br />
        <%= f.submit "Post", class: 'btn btn-primary' %>
    <% end %>
    <br />
</div>

app/views/products/new.html.erb
<div class="booyah-box col-10 offset-1">
    <h1>Add Your New Clothes</h1>
    <%= simple_form_for root_path do |f| %>
        <%= f.input :product %>
        <%= f.input :cost %>
        <br />
        <%= f.submit 'Post', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/products/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= @product.product %></h1>
</div>